### ISSUE TITLE
Remove unnecessary string slicing

### ISSUE THREAD

**Issue by sankalp-khare** [annanymaus/babysteps#1]
https://github.com/annanymaus/babysteps/blob/eb41d9b19cd9c1b4c6da1e2aeaa33eba1fcafd78/palindrome.py#L7

```
>>> "sankalp"[::1] == "sankalp"
True
```
=> We should just make it:
```
if (n == n[::-1]):
```

**Comment by annanymaus** [comment]
Done. Thanks so much!
